name: Build and Push to GHCR

on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: masonjames/platform-infra/.github/workflows/ghcr-build-webhook.yml@main
    permissions:
      contents: read
      packages: write
    with:
      deploy_on_branch: 'dev'
    secrets: inherit
